name: Make release
on:
    push:

# on:
#   workflow_run:
#     workflows: ["Build executable"]
#     types: [completed]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: C
        run: touch CCCC
      - name: D
        run: touch DDDD
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            *
  
  release:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}

    
    steps:

      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          # draft: false
          # prerelease: false

      # - name: Download artifact
      #   uses: actions/download-artifact@v4
          
      - name: Display structure of downloaded files
        run: ls -R
